version: 0.2

phases:
  install:
    commands:
      - echo installing packages...
      - npm install --global yarn
      - yarn install
  build:
    commands:
      - echo running tests...
      - yarn jest
      - echo building...
      - yarn build

artifacts:
  files:
    - $CODEBUILD_SRC_DIR/dist/prod/*